DROP DATABASE IF EXISTS PRACTICE2;
CREATE DATABASE PRACTICE2;
USE PRACTICE2;
CREATE TABLE MEMBERS(
    MEMBER_ID INT AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY(MEMBER_ID),
    MEMBER_NAME VARCHAR(50) NOT NULL,
    EMAIL DATETIME DEFAULT NOW(),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);
CREATE TABLE PRODUCTS(
    PRODUCT_ID INT AUTO_INCREMENT, 
    CONSTRAINT PRIMARY KEY(PRODUCT_ID),
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    PRICE INT UNSIGNED NOT NULL,
    STOCK INT DEFAULT 0 NOT NULL,
    CREATED_AT DATETIME DEFAULT NOW()
);
CREATE TABLE ORDERS(
    ORDER_ID BIGINT AUTO_INCREMENT,
    CONSTRAINT PRIMARY KEY (ORDER_ID),
    MEMBER_ID INT, 
    CONSTRAINT FOREIGN KEY(MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID),
    ORDER_DATE DATETIME DEFAULT NOW()
);
CREATE TABLE ORDER_ITEMS(
    ITEM_ID INT AUTO_INCREMENT, 
    CONSTRAINT PRIMARY KEY(ITEM_ID),
    ORDER_ID BIGINT,
    CONSTRAINT FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    PRODUCT_ID INT,
    CONSTRAINT FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    QUANTITY INT DEFAULT 1,
    PRICE INT UNSIGNED NOT NULL
);
CREATE TABLE STUDENTS(
    STUDENT_ID VARCHAR(10), 
    CONSTRAINT PRIMARY KEY(STUDENT_ID),
    STUDENT_NAME VARCHAR(30) NOT NULL,
    MAJOR VARCHAR(50),
    GRADE TINYINT UNSIGNED,
    ENROLLED_DATE DATE
);
CREATE TABLE EMPLOYEES(
    EMP_ID INT AUTO_INCREMENT, 
    CONSTRAINT PRIMARY KEY(EMP_ID),
    EMP_NAME VARCHAR(40) NOT NULL,
    SALARY INT UNSIGNED NOT NULL,
    HIRE_DATE DATE NOT NULL,
    DEPARTMENT VARCHAR(50)
);
CREATE TABLE BOARDS(
    BOARD_ID INT AUTO_INCREMENT, 
    CONSTRAINT PRIMARY KEY(BOARD_ID),
    TITLE VARCHAR(200) NOT NULL,
    CONTENT TEXT NOT NULL,
    WRITER_ID INT,
    CONSTRAINT FOREIGN KEY(WRITER_ID) REFERENCES MEMBERS(MEMBER_ID),
    CREATED_AT DATETIME DEFAULT NOW()
);
CREATE TABLE COMMENTS(
    COMMENT_ID INT AUTO_INCREMENT, 
    CONSTRAINT PRIMARY KEY(COMMENT_ID),
    BOARD_ID INT,
    CONSTRAINT FOREIGN KEY(BOARD_ID) REFERENCES BOARDS(BOARD_ID),
    WRITER_ID INT,
    CONSTRAINT FOREIGN KEY(WRITER_ID) REFERENCES MEMBERS(MEMBER_ID),
    CONTENT VARCHAR(300) NOT NULL,
    CREATED_AT DATETIME DEFAULT NOW()
);
CREATE TABLE PAYMENTS(
    PAYMENT_ID BIGINT AUTO_INCREMENT, 
    CONSTRAINT PRIMARY KEY(PAYMENT_ID),
    ORDER_ID BIGINT,
    CONSTRAINT FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    PAYMENT_AMOUNT INT UNSIGNED NOT NULL,
    PAYMENY_METHOD VARCHAR(30),
    PAYMENT_DATE DATETIME DEFAULT NOW()
);
CREATE TABLE REVIEWS(
    REVIEW_ID INT AUTO_INCREMENT, 
    CONSTRAINT PRIMARY KEY(REVIEW_ID),
    PRODUCT_ID INT,
    CONSTRAINT FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    MEMBER_ID INT,
    CONSTRAINT FOREIGN KEY(MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID),
    RATING TINYINT UNSIGNED NOT NULL,
    REVIEW_TEXT TEXT,
    CREATED_AT DATETIME DEFAULT NOW()
);